#!/bin/bash

if [ $# -eq 0 ]
then
    cat <<EOF

Delete the given artists from the database.  Names with spaces must be quoted.

Usage:

  $0 U2 "The Beatles"

EOF
    exit 1
fi

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARAMS=""
for PARAM in "$@"
do
  PARAMS="${PARAMS} \"${PARAM}\""
done
source env/bin/activate
bash -c "PYTHONPATH=src python src/uykfg/drop.py $PARAMS"


